config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/edit'
  get 'users/new'
  get 'users/show'
  #root 'posts#index'
  #get 'posts', controller: 'posts', action: 'edit', id: 1
  #get 'posts' => 'posts#edit',id: 1
  #get 'home', to: 'post#show', constraints: {id: /[A-Z]\d{5}/}
  #get :home => 'posts#index'
  #get home: 'posts#index'

  #get 'posts(/:id)', to: 'posts#show'  --if /posts/1 is searched it will not find an action named 1 so
                                        #it will go to action show and use 1 as id in params[:id]

  #an example
  #get 'photos/:id/:user_id', to: 'photos#show' --if we pass /photos/1/2 then 1 will be params[:id] and
                                                # and 2 will me params[:user_id]
  #get 'photos/:id/with_user/:user_id', to: 'photos#show'
  #This route would respond to paths such as /photos/1/with_user/2. In this case, params would be { controller: 'photos', action: 'show', id: '1', user_id: '2' }.

  #get 'exit', to: 'sessions#destroy', as: :logout
  #This will create logout_path and logout_url as named route helpers in your application. Calling logout_path will return /exit

  #match 'photos', to: 'photos#show', via: [:get, :post]
                        #OR
  #get 'photos', to: 'photos#show'
  #post 'photos', to: 'photos#show'

  #resources :magzine do
 #   resources :photos, only: [:index, :new, :create]
 # end
  #resources :photos, only: [:show, :edit, :update, :destroy]
  
  resources :magzine , shallow: true do
    resources :photos
  end
  resources :posts, path: '' do
    #put :default_body on: :member
            #OR
    member do
      put :default_body
    end
    #delete :delete_all on: :collection
              #OR
    collection do
      delete :delete_all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :find_post, only: [:show, :edit, :update, :destroy, :default_body]
    def index
        @posts = Post.all
    end

    def new
        @post = Post.new
    end

    def create
        @post= Post.new(post_params)
        if @post.save
            redirect_to post_path(@post), :notice => "User saved"
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end

    def delete_all
        Post.delete_all
        redirect_to root_path
    end

    def default_body
        @post.body="this is default body"

        if @post.save
            redirect_to @post #same as post_path(@path)
        else
            render 'show'
        end

    end

    def update
        if @post.update(post_params)
            redirect_to post_path(@post)
        else
            render 'edit'
        end
    end

    def destroy
        @post.destroy
        redirect_to root_path
    end

    private
      def post_params
          params.require(:post).permit(:title, :body)
      end

      def find_post
          @post=Post.find(params[:id])
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def edit
  end

  def new

  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <%= link_to "home",posts_path%>
    <%= %>
    <%= link_to "new post", new_post_path%>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f|%>
    <%=f.label :title %>
    <%=f.text_field :title %><br><br>

    <%=f.label :body %>
    <%=f.text_area :body %><br>
    <br>
    <%= f.submit %>
    <br>
<% end %>

app/views/posts/edit.html.erb
<h1>edit post</h1>
<%=render 'form'%>

app/views/posts/index.html.erb
<h1>Index Page</h1>
<%@posts.each do |post|%>
    <%= link_to post.title, post_path(post) %><br>
    <%=post.body%><br>
<%end%>
<%=link_to 'delete_all', delete_all_posts_path, method: :delete, data: {confirm: 'are you sure?'} %>

app/views/posts/new.html.erb
<h1>New post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>show page</h1>
<%=@post.title%><br>
<%=@post.body%><br>
<%=link_to "edit", edit_post_path(@post)%><br>
<%=link_to "defalut body", default_body_post_path(@post), method: :put %><br>
<%=link_to "delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %><br>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>